// Package reporter provides functionality to output and format drift reports
// generated by the drift checker. It defines interfaces for writing reports
// to various output destinations such as files, databases, or external services.
package reporter

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 -generate
import (
	"context"
	"drift-watcher/pkg/services/driftchecker"
)

// OutputWriter defines the interface for writing drift reports to various output destinations.
// Implementations of this interface should handle the formatting and output of drift reports
// to different mediums such as files, databases, logging systems, or external services.
//
//counterfeiter:generate . OutputWriter
type OutputWriter interface {
	WriteReport(ctx context.Context, report *driftchecker.DriftReport) error
}
